add mentor
htmlacademy-javascript/1443603-kekstagram-28 pull request #1
Opened 2023-02-18 09:11 UTC by makarichevss

2023-02-19 13:30 UTC, pavel-nyukalo requested changes

2023-02-19 13:30 UTC, pavel-nyukalo commented on Readme.md
> +* Наставник: `Павел Нюкало`.
Давай потренируемся в `markdown` и сделаем единообразно - мне тоже добавим ссылку, по аналогии с твоей - `[текст ссылки](сама ссылка)`

2023-02-19 17:11 UTC, makarichevss commented on Readme.md
> +* Наставник: `Павел Нюкало`.
Добавил ссылку на твой профиль Академии

2023-02-20 05:55 UTC, pavel-nyukalo approved these changes

2023-02-20 05:56 UTC, merged